// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import ReactConnectController from "./react_connect_controller"
application.register("react-connect", ReactConnectController)
